Entiteiten & attributten volgens ERD
daan-bit/ipmedth-groep4 pull request #1
Opened 2022-11-22 09:01 UTC by prgnl

Tabellen, entiteiten en attributen volgens ERD. 
Tabel teacher_has_classes is een many to many relatie zoals eerder besproken.
I.p.v. groups **uiteindelijk** voor gekozen om classes te gebruiken als entiteit naam, zorgde voor problemen in SQL. 
![ApplicationFrameHost_lQd8YxOjFu](https://user-images.githubusercontent.com/21337504/203270638-fe089fb8-0243-4b93-ac79-fdd758fb1214.png)

2022-11-22 09:41 UTC, daan-bit requested changes
Paar kleine dingetjes. Ziet er verder goed uit

2022-11-22 09:41 UTC, daan-bit commented on database/migrations/2022_11_21_182221_create_classes_table.php
> +            $table->foreign('school_id')->references('id')->on('schools');
Waarom heeft classes een fk naar schools niet naar users?

2022-11-22 09:41 UTC, daan-bit commented on database/migrations/2022_11_21_215557_create_exercises_table.php
> +        Schema::create('exercises', function (Blueprint $table) {
Ik zou excersises veranderen naar assignments

2022-11-22 13:54 UTC, Kasper-Trouwee requested changes
Het ziet er prima uit alleen paar kleine dingen.

BTW ik zou naast de `migrations` ook `seeders` aanmaken zodat we makkelijk lokaal kunnen testen.

2022-11-22 13:54 UTC, Kasper-Trouwee commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->string('username')->unique();
De `username` kan toch niet unique zijn want zo kan er een `pietje` in klas 3a zijn en een `pietje` in klas 3b

2022-11-22 13:54 UTC, Kasper-Trouwee commented on database/migrations/2022_11_21_182221_create_classes_table.php
> +            $table->foreign('school_id')->references('id')->on('schools');
Dit klopt want kinderen kunnen maar 1 klas hebben maar wel meerdere leraren

2022-11-22 13:54 UTC, Kasper-Trouwee commented on database/migrations/2022_11_21_214740_create_students_table.php
> +            $table->string('first_name', 100);
Kan dit gewoon niet de `username` zijn van de `user table`?

2022-11-22 13:54 UTC, Kasper-Trouwee commented on database/migrations/2022_11_21_215557_create_exercises_table.php
> +        Schema::create('exercises', function (Blueprint $table) {
Ik denk dat ook beter is want `excercises` zou ook kunnen refereren naar oefeningen

2022-11-22 13:55 UTC, Kasper-Trouwee commented on database/migrations/2022_11_21_220649_create_results_table.php
> +        //test
Vergeet deze line niet te verwijderen

2022-11-23 12:34 UTC, Tycho-02 requested changes

2022-11-23 12:34 UTC, Tycho-02 commented on database/migrations/2022_11_21_180726_create_schools_table.php
> +            $table->string('postal_code', 7);
Postcode heeft 6 tekens

2022-11-24 09:29 UTC, prgnl commented on database/migrations/2022_11_21_214740_create_students_table.php
> +            $table->string('first_name', 100);
nee, het is beter als wij het consistent houden met de id's als foreign keys ipv strings. Ook willen we de username niet meer unique hebben in users table wat betekent dat er twee pietjes met zelfde username zouden kunnen zijn wat een foutmelding zou opleveren

2022-11-25 10:25 UTC, Kasper-Trouwee approved these changes

2022-11-25 10:31 UTC, daan-bit approved these changes

2022-11-25 10:31 UTC, merged