At 30 als docent wil ik kunnen inloggen zodat ik groepen en leerlingen kan beheren
daan-bit/ipmedth-groep4 pull request #3
Opened 2022-11-29 12:31 UTC by daan-bit

Docent kan inloggen met username
Wordt geredirect naar docent overview pagina
Middleware toegevoegd
Base styling terug toegevoegd

2022-11-29 12:41 UTC, alexf-nl approved these changes
lgtm

2022-11-29 16:50 UTC, Tycho-02 requested changes

2022-11-29 16:50 UTC, Tycho-02 commented on app/Http/Requests/Auth/StudentRequest.php
> +        return true;
Moet deze altijd "true" returnen?

2022-11-29 16:50 UTC, Tycho-02 commented on app/Http/Controllers/TeacherController.php
> +        return Inertia::render('Teachers/Overview', ['teacher' => $teacher]);
Wat gebeurt er als er niks terug komt in $teacher?

2022-11-29 16:50 UTC, Tycho-02 commented on app/Http/Controllers/StudentController.php
> +            error_log('hoi');
hoi?

2022-11-29 16:52 UTC, Tycho-02 commented
@daan-bit, @prgnl, @Kasper-Trouwee Waarom gebruiken we niet BEM voor class namen?

2022-11-30 08:20 UTC, Kasper-Trouwee reviewed
Tycho snapt het

2022-11-30 08:25 UTC, merged