At 31 als admin wil ik kunnen inloggen zodat ik docenten kan beheren
daan-bit/ipmedth-groep4 pull request #4
Opened 2022-11-29 13:09 UTC by daan-bit

Admin kan inloggen
En middleware toegepast

2022-11-29 15:34 UTC, alexf-nl approved these changes
LGTM. Code uit mijn branch is nog niet helemaal klaar, dus voor de rest die pull request moet goedkeuren houdt daar rekening mee (bijvoorbeeld resources/js/Pages/Students/Login.jsx bestand)

2022-11-29 16:57 UTC, Tycho-02 requested changes

2022-11-29 16:57 UTC, Tycho-02 commented on resources/js/Pages/Students/UserLogin.jsx
> +                                        Geen student gevonden met deze id.
deze -> dit

2022-11-29 16:57 UTC, Tycho-02 commented on resources/js/Pages/Students/UserLogin.jsx
> +        console.log('gesubmit');
console.logs staan altijd een beetje onprofessioneel

2022-11-29 16:57 UTC, Tycho-02 commented on resources/js/Pages/Students/UserLogin.jsx
> +    console.log(students);
console.logs staan altijd een beetje onprofessioneel

2022-11-29 16:57 UTC, Tycho-02 commented on resources/js/Pages/Students/Login.jsx
> +                                        No students found.
Engels!?

2022-11-29 16:57 UTC, Tycho-02 commented on resources/css/app.css
> +@tailwind utilities;
We gaan toch geen f*cking tailwind gebruiken!!?

2022-11-30 07:18 UTC, Tycho-02 commented on resources/js/Pages/Students/Login.jsx
> +                        </tbody>
Je kan beter geen table meer gebruiken want deze kan je niet responsive stylen, je kan beter gebruik maken van flexbox

2022-11-30 08:23 UTC, Kasper-Trouwee approved these changes

2022-11-30 08:25 UTC, merged